### ISSUE TITLE
Ethernet support

### ISSUE THREAD

**Issue by TheYigidOS** [pedros89/ESP32-OTA-update-SPIFFS-with-Arduino#1]
Hi i use esp32 with ethernet. how i use this ota with ethernet (enc28j60)

**Comment by pedros89** [comment]
I use esp32 with WiFi. I have never tried ethernet support. As long as there is internet connection just run the function and you should be able to:
- connect to the server
- download the file 
- install the file
Just running the function

**Comment by TheYigidOS** [comment]
how i download program?

**Comment by pedros89** [comment]
I suggest you use this
https://github.com/pedros89/ESP32-update-both-OTA-Firmware-and-OTA-SPIFFS-with-Arduino
Just copy paste the .ino file content in your Arduino and call the function to update in the setup or where you wish to call them. Make sure you install all the library requested

**Comment by TheYigidOS** [comment]
i see this thing before but i need with ethernet

**Comment by TheYigidOS** [comment]
there is a way with ethernet and ssl?

**Comment by pedros89** [comment]
As long as Esp is connected to the internet it should work

**Comment by TheYigidOS** [comment]
just wire the enc28j60 and import lib?

**Comment by pedros89** [comment]
Yes
