### ISSUE TITLE
RESET mcu

### ISSUE THREAD

**Issue by TheYigidOS** [pedros89/ESP32-OTA-update-SPIFFS-with-Arduino#2]
hi if i reset mcu it use firmware from storage or get one more time from url on every boot

**Comment by pedros89** [comment]
If you reset the MCU while updating you will find your MCU with spiffs memory cancelled and the MCU will automatically create an empty SPIFFS partition. You will lose storage so you had better make a flag saved in EEPRON that is set to true if update was unsuccessful so the ESP will repeat  the update process at start up.

**Comment by TheYigidOS** [comment]
i mean, mcu  gets firmware from server even if no update, or if there is no update it use from storage

**Comment by pedros89** [comment]
Yes if you will activate that function the esp will get from server the update even if there is no update. You have to do for example a POST request to the server sending the current firmware name, and have the server reply with the  firmware name stored online on the server, if the version is upper the update is available and you can call the function

**Comment by TheYigidOS** [comment]
thank u, U make awsome job!
